Added BaseActivity class and adjusted other classes to inherit
TTUSDC/android-testprep-game pull request #4
Opened 2017-03-06 23:09 UTC by dlowrey

## Description

## Related Issue(s)

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (documentation, refactoring, basically not a feature or a bug fix)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-03-06 23:11 UTC, dlowrey commented
@asclines I added the class I forgot to add last time. Can you review/merge?

2017-03-07 04:37 UTC, asclines requested changes
For future reference, you don't need the whole body of the PR template. Just the parts you actually fill out

2017-03-07 04:37 UTC, asclines commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/BaseActivity.java
> + * Created by Dane Lowrey on 3/6/2017.
remove this

2017-03-07 15:55 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/BaseActivity.java
> + * Created by Dane Lowrey on 3/6/2017.
I could have sworn I changed those settings. Ugh.

2017-03-07 19:08 UTC, asclines approved these changes

2017-03-07 19:08 UTC, merged