Started CreateAccount feature.
TTUSDC/android-testprep-game pull request #7
Opened 2017-04-06 00:28 UTC by joshuaj1397

Started Create_Account Feature

2017-04-06 11:53 UTC, asclines reviewed
Looking good so far.

2017-04-06 11:53 UTC, asclines commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> + * Created by lamsa on 4/5/2017.
Remove this.

2017-04-06 11:53 UTC, asclines commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +        // Instantiate LoginPresenter
Doesn't look like anything is being instantiated.

2017-04-06 11:53 UTC, asclines commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountPresenter.java
> + * Created by lamsa on 4/5/2017.
Remove this.

2017-04-06 11:53 UTC, asclines commented on app/src/main/res/values/strings.xml
> +    <string name="createAccount_hint_first_name">First Name</string>
`createAccount` => `create_account`. Keep it all snake_case.

2017-04-06 11:53 UTC, asclines commented on app/src/main/res/values/strings.xml
> +    <string name="createAccount_hint_last_name">Last Name</string>
`createAccount` => `create_account`. Keep it all snake_case.

2017-04-06 11:53 UTC, asclines commented on app/src/main/res/values/strings.xml
> +    <string name="createAccount_hint_username">Username</string>
`createAccount` => `create_account`. Keep it all snake_case.

2017-04-06 18:28 UTC, dlowrey requested changes

2017-04-06 18:28 UTC, dlowrey commented on app/build.gradle
> +    compile 'com.android.support:support-annotations:25.2.0'
Remove this, I will deal withthe `@NonNull` and `@Nullable` imports later on.

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +    @BindView(R.id.firstName) String mfirstName;
See [Google's Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) under **Camel case: defined**

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +    @BindView(R.id.lastName) String mlastName;
See [Google's Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) under **Camel case: defined**

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/Login/LoginInterface.java
> +        void createActivity(Intent activity);
This method's arguments should be `Context`, not `Intent`, this way we keep the View as dumb as possible (i.e, it won't have to create an intent to pass to the presenter).

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/Login/LoginActivity.java
> +        mPresenter.createActivity(createAccount);
Change the method in `mPresenter` to take in `Context` as an argument instead of an Intent, so we can keep the view as dumb as possible.

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/res/values/strings.xml
>      <string name="login_invalid_password">Invalid Password</string>
Get rid of this string resource copied from the login feature and create resources related to Create Account's functionality.

2017-04-06 18:28 UTC, dlowrey commented on app/src/main/res/values/strings.xml
>      <string name="login_invalid_email">Email or Username is invalid</string>
Get rid of this string resource copied from the login feature and create resources related to Create Account's functionality.

2017-04-06 20:49 UTC, asclines commented on app/build.gradle
> +    compile 'com.android.support:support-annotations:25.2.0'
Whats wrong with now?

2017-04-13 02:07 UTC, dlowrey commented
@joshuaj1397 I noticed you fixed a few more things before we left the meeting. Go ahead and push those as well before we review.

2017-04-13 16:32 UTC, asclines requested changes
Put TODOs to remind yourself about the parts that aren't implemented or finished. That way you don't forget anything. 

Example:
```
TODO(asclines): Add exception handling here
```

2017-04-13 18:20 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +    Button mFirstName;
This isn't supposed to be a Button is it?

2017-04-13 18:20 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +    Button mLastName;
This isn't supposed to be a Button is it?

2017-04-13 18:20 UTC, dlowrey commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountActivity.java
> +    Button mUsername;
This isn't supposed to be a Button is it?

2017-04-20 02:47 UTC, asclines requested changes

2017-04-20 02:47 UTC, asclines commented on app/src/main/java/org/sdc/ttu/sdc_test_game_app/CreateAccount/CreateAccountPresenter.java
> +    public void createAccount(String firstName, String String, String userName, String password) {
`String String`? Should this be `String lastName`?

2017-04-20 02:47 UTC, asclines commented on app/src/main/res/layout/activity_create_account.xml
> +            android:layout_weight="7.11" />
Why `7.11`?

2017-04-20 04:02 UTC, dlowrey commented on app/src/main/res/layout/activity_create_account.xml
> +            android:layout_weight="7.11" />
@asclines I think they created this layout with the Designer

2017-04-20 04:02 UTC, dlowrey submitted a review, later dismissed

2017-04-27 01:08 UTC, merged